version: "3.8"
services:
    web:
        container_name: nginx
        build:
            context: ./nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/root:/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    db:
        container_name: postgresql
        build:
            context: ./postgresql
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerpass
            POSTGRES_DB: mydatabase
volumes:
    postgres_data:
