version: "3.8"
services:
    web:
        container_name: nginx
        build:
            context: ./nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./src:/usr/share/nginx
    db:
        container_name: postgresql
        build:
            context: ./postgresql
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerpass
            POSTGRES_DB: mydatabase
    php:
        container_name: php
        build:
            context: ./php
        ports:
            - "9000:9000"
        volumes:
            # - ./php/php-fpm.ini:/usr/local/etc/php/conf.d/php-fpm.ini
            - ./src:/usr/share/nginx
